### ISSUE TITLE
Re: backup software

### ISSUE THREAD

**Issue by karlicoss** [albertz/wiki#1]
Hey, I'm the author of [this](https://news.ycombinator.com/item?id=22160572) HN post, saw your comment. Great that you keep a public wiki, wish more people did that!

I figured github issue would be the easiest way of communication! Feel free to simply close the issue afterwards if you want.

I'm using borg backup (it's mentioned in your list), and it's awesome, I highly recommend using it if you're still not sure what to use!

> Certain files are more important than others

For the most part I simply backup everything that makes sense to back up without trying too much to weed out the bits that don't necessarily need to be backed up. You'd probably spend more time trying to do that instead of bying a bigger external drive.

> I want to keep several copies around. Not all copy must be complete, they could maybe just have the important files.

Yep, I'm using similar approach.

- I don't back up heavy stuff that can be downloaded again at all (e.g. software packages/youtube videos/etc). The only thing I'm doing is running 'tree' command against my whole filesystem automatically, so if my drive crashes, I'd know what I've lost.
- I've got SSD and HDD in my computer, and most of important data is on SSD, I back it up onto the HDD overnight (automatically, in cron). It's quite unlikely both drives crash simultaneously.
- in addition, I've got couple of external drives that I alternate and also keep borg backups on them

> Copying will take long, because of huge amounts of data. There has to be some continuous update.

Borg is [very efficient](https://borgbackup.readthedocs.io/en/stable/#main-features) and deduplicating, so it would only copy data that changed (and compress it every efficienltly). Each time I run borg onto my external drive, it only takes couple of minutes even though it's hundreds of gigabytes of backed up data. It's not continuous though, but if you make it periodic enough, it'll be almost continuous :) 

> Although it is not totally clear whether the backup system should have its own versioning support. 

Borg does that, you can access (in fact, mount as a filesystem) any snapsot

> Backups on external cloud storage would be nice as well, but should be encrypted there

Borg supports encryption, and some cloud backup providers have support for Borg (although I haven't had time to set it up yet)

> Some overview where I have what backup, and which files are there, and maybe even the version of them, would be useful.

Yes! I wish backup systems offered it from the box. I have some wrapper script that creates a file in the 'roots' of the backed up directories, containing information on the data and which drive was it backed up to.

As for data, I've seen you linked some tools of your own, which I'll check out later, but [here's](https://beepb00p.xyz/my-data.html#why) a list of stuff I export and back up in case you find any of these tools useful!

**Comment by albertz** [comment]
Hey, thanks for your response here. Such input is indeed helpful. I appreciate that. I got so much recommendations for Borg now that I really should try that out.

I haven't really thought about how to deal with GitHub issues here for this repo, but I guess using it as public comments to some of the content make sense. No idea if I should close it or not. I'll just leave it open for now. Maybe at some later point I'll close it, to keep it clean.

[Your website](https://beepb00p.xyz/) is actually quite similar in principle to this repo, just with a different format, and you have already much more content. I also have much more in my private documents. Maybe I should publish more of that, although it's very mixed up with private stuff.

**Comment by albertz** [comment]
Btw, about lifelogging, I have implemented my own simple desktop time tracker, which tracks the open program and what file (or directory, or URL) is opened. That is my [TimeCapture project](https://github.com/albertz/TimeCapture), which is basically always running.
I see that you listed [arbtt-capture](https://arbtt.nomeata.de/). Maybe I should also try that.

**Comment by karlicoss** [comment]
Yep, mixing with private stuff is also what prevents me from publishing all of my wiki notes (the ones that are published now are just more carefully curated). Still thinking about best way to handle this.

Arbtt is good! Although I can see that first commit to your tool was 9 years ago -- very impressive lifelogging track :)

**Comment by albertz** [comment]
I just checked, my first TimeCapture entry is from 2011-03-13, and it goes on until today (every day is a single file), and these logs are about 1.8GB in size now. :) (Pure text. Maybe I should compress it automatically when a day is over.)

About your notes, do you have a common database, or filesystem, or whatever system where you store them all, no matter if private or public, and you have some flag or meta-info somewhere where you specify whether it is public or private? I thought about doing sth like that, but never did, and maybe it is overkill. So I manually would move stuff over to this public wiki now when I think it can be public. But as you see, there is not too much content here yet. Recently I also often use Google Docs to write up notes, simply because of laziness, because then it's pretty simple to access from everywhere, from my phone, etc., which is a feature I often want (because you often get good ideas when you don't have a computer nearby, except of your phone). So now my notes and documents are even more scattered than before.

**Comment by albertz** [comment]
Small question about arbtt: It does not store the opened file or web URL, right? That is one of the main features of my TimeCapture. I don't just want to know which apps I use how often. I want to see which websites I visit how often, and what files (or projects, which I can derive from the directory) I did work on, for how long. I can automatically generate time reports per project based on that (in theory; I never actually did that...).

This [foreground_app_info library](https://github.com/albertz/foreground_app_info/) is the base behind that.

**Comment by karlicoss** [comment]
> Small question about arbtt: It does not store the opened file or web URL, right

Ah, yeah, that's true. It does capture window title though, so if your text editor/IDE/terminal sets it to reflect current directory/file, it woudl be captured as well.  And for browing history I'm personally just backing up all of my browsing history (just copying the databases), so I have it anyway.

**Comment by karlicoss** [comment]
> About your notes, do you have a common database, or filesystem, or whatever system where you store them all, no matter if private or public

I'm keeping pretty much all of them in org-mode; for the website they are rendered by org-export function. By default it export everything except items that have "noexport" tag, that's how I'm handling private notes for my blog at the moment. The private notes that I have in my blog source files are not sensitive information though, so if something broke and they got exported, worst case I just end up with ugly unedited stuff published.

Whereas in my personal wiki some of the notes have more sensitive information (i.e. refer to specific people, etc), which I'd rather not expose by accident. So just have to think of an easy way to make sure it doesn't get leaked :)

As for multiple devices -- emacs is always there on my computers (also org-capture is very helpful in making sure it's very easy to add new information without distractions). On my Android I'm using Orgzly app and it's all syncronized by Syncthing (or you can use Dropbox); so I don't end up scattering notes.

**Comment by albertz** [comment]
I see. But then you have some (all the private) notes now in your personal wiki, while other (public + incomplete/noexport) notes are for your website, so already scattered in 2 different places, right? Is there never the case when you want to move something from your personal wiki to the public website? Or also sometimes overlaps in topics, and you want to crosslink?

**Comment by karlicoss** [comment]
Ah, yep, I guess I mean they are not scattered in terms of different apps/products -- they are just plain directories next to each other in the filesystem.

E.g. my search functions/todo list agenda/etc are just accumulated from both of these directories.

Same for moving: [org-refile](https://orgmode.org/manual/Refile-and-copy.html) allows for quick moving of org-mode headings (with its metdata/children etc) between files and headings. 

So for example, most of my blog pages (especially drafts), got special heading which I name 'Amendements'. So often when I process my bookmarks, I just press 'refile' hotkey, start typing page name (e.g. 'pkm-search' for the post from HN), and the 'Amendements' heading shows up so I press enter and the link/note is moved.

For cross-linking -- I actually don't cross link that much in my private notes (they are quite chaotic), but it's also doable in org-mode, e.g. with [custom link types](https://orgmode.org/manual/Adding-hyperlink-types.html). I think there are even easier ways to do it (e.g. there are some interactive functions for linking), I just didn't get to learn about them yet :)
